# The warewulf rpm pulls in nfs-utils, dhcp, and tftp-server
---
- name: Install epel-release
  ansible.builtin.dnf:
    name: epel-release
    state: latest
- name: Install epel rpms
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - gnome-extensions-app
    - gnome-shell-extension-caffeine
- name: Install warewulf rpms
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    disable_gpg_check: true
  with_items:
    - "{{ ww_rpm_url }}"
    # - "{{ ww_dracut_rpm_url }}"
- name: Configure enp2s0
  ansible.builtin.shell:
    cmd: "{{ item }}"
  with_items:
    - nmcli con down enp2s0
    - nmcli con modify enp2s0 ipv4.addresses "10.0.0.1/16"
    - nmcli con modify enp2s0 ipv4.method manual
    - nmcli con modify enp2s0 ipv6.method link-local
    - nmcli con modify enp2s0 connection.autoconnect yes
    - nmcli con up enp2s0
- name: Copy warewulf.conf
  ansible.builtin.copy:
    src: etc/warewulf/warewulf.conf
    dest: /etc/warewulf/warewulf.conf
    owner: root
    group: root
    mode: 0644
